### ISSUE TITLE
ImportError: No module named meta.python

### ISSUE THREAD

**Issue by GloryPassarello** [mapzen/tileserver#107]
Hello! Many thanks for all this works!
while I was installing tileserver, I run into this error: 
`Traceback (most recent call last):
  File "tileserver/__init__.py", line 404, in <module>
    tile_server = create_tileserver_from_config(config)
  File "tileserver/__init__.py", line 375, in create_tileserver_from_config
    output_calc_mapping = make_output_calc_mapping(yaml_config)
  File "/home/gloria/env/local/lib/python2.7/site-packages/tilequeue/command.py", line 554, in make_output_calc_mapping
    from vectordatasource.meta.python import make_function_name_props
ImportError: No module named meta.python`

I have followed instruction reported here:  https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service 

the error I got is the output of `python tileserver/__init__.py config.yaml`.
I am using a virtual machine with Ubuntu 14.04.
What should I do to fix it?

**Comment by rmarianski** [comment]
That error suggests that you don't have the latest version of the vector-datasource repo installed. Can you verify that it is indeed the latest master and that it's picking up the location you expect? `python -c 'import vectordatasource; print vectordatasource.__file__'`

Alternatively, you can use the latest [tagged version](https://github.com/tilezen/vector-datasource/releases) and ensure that you have the exact dependencies that are mentioned.

**Comment by GloryPassarello** [comment]
Hello!
I had this output: 

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named vectordatasource`

What should I do to install it? 
Many thanks

**Comment by rmarianski** [comment]
```shell
git clone https://github.com/mapzen/vector-datasource.git
cd vector-datasource
python setup.py develop
```

**Comment by GloryPassarello** [comment]
Hi again,

**Comment by GloryPassarello** [comment]
Hi! Many thanks!
I have `vector-datasource==1.4.0` now but this does not solve the issue...

**Comment by rmarianski** [comment]
And the matching versions as well? See [release notes](https://github.com/tilezen/vector-datasource/releases/tag/v1.4.0).

`tileserver v2.1.0 and tilequeue v1.8.0 and mapbox-vector-tile v1.2.0`

**Comment by GloryPassarello** [comment]
Hi! I have ` tilequeue v1.8.0 and mapbox-vector-tile v1.2.0` now...
Running  ` python tileserver/__init__.py config.yaml`, 
I got another error:
`Traceback (most recent call last):
  File "tileserver/__init__.py", line 4, in <module>
    from tilequeue.command import make_output_calc_mapping
ImportError: cannot import name make_output_calc_mapping`

**Comment by nvkelso** [comment]
@GloryPassarello Do you have those tags checked out? I suspect you have master checked out instead in 1 or more of the repos.

**Comment by nvkelso** [comment]
For instance, you'd need to checkout the latest release in this repo:

https://github.com/tilezen/tileserver/releases/tag/v2.1.0

**Comment by rmarianski** [comment]
Based on that error it looks like you have tileserver master checked out. You'll want 2.1.0 of tileserver.

**Comment by gabefair** [comment]
@GloryPassarello  did installing v2.1.0 of tileserver fix your issue?

**Comment by nvkelso** [comment]
Closing for inactivity.
