### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by pnorman** [mapzen/tileserver#119]
```
(ve) pnorman@pippin:~/osm/tilezen/ve$ pip install tileserver==2.1.0
Collecting tileserver==2.1.0
  Using cached tileserver-2.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HUCgBa/tileserver/setup.py", line 5, in <module>
        with open(version_path) as fh:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-HUCgBa/tileserver/VERSION'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-HUCgBa/tileserver/
```

This is in a clean virtualenv

**Comment by pnorman** [comment]
Looking at the .tar.gz from pypi, it doesn't have the VERSION file in it.

**Comment by rmarianski** [comment]
This should work now with tileserver 2.1.1.
