### ISSUE TITLE
Unknown WKB type 49

### ISSUE THREAD

**Issue by divya1c** [mapzen/tileserver#16]
Hi! 

I get this error and backtrace when I try requesting tiles from my mapzen tile server.

127.0.0.1 - - [19/Feb/2016 15:13:17] "GET /all/15/9644/12322.json HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/divya/Documents/oneconcern/Vector-tile-server/Mapzen/tileserver/tileserver/**init**.py", line 187, in **call**
    response = self.handle_request(request)
  File "/Users/divya/Documents/oneconcern/Vector-tile-server/Mapzen/tileserver/tileserver/**init**.py", line 283, in handle_request
    [])
  File "/usr/local/lib/python2.7/site-packages/tilequeue-0.7.1-py2.7.egg/tilequeue/process.py", line 323, in process_coord
    feature_layers = _preprocess_data(feature_layers, shape_padded_bounds)
  File "/usr/local/lib/python2.7/site-packages/tilequeue-0.7.1-py2.7.egg/tilequeue/process.py", line 26, in _preprocess_data
    shape = loads(wkb)
  File "/usr/local/lib/python2.7/site-packages/shapely/wkb.py", line 16, in loads
    return reader.read(data)
  File "/usr/local/lib/python2.7/site-packages/shapely/geos.py", line 427, in read
    raise ReadingError("Could not create geometry because of errors "
ReadingError: Could not create geometry because of errors while reading input.
ParseException: Unknown WKB type 49

Why am I getting this? Does this mean something is wrong with my data?  I am using psql (PostgreSQL) 9.5.0 as my db.
Thanks!

**Comment by divya1c** [comment]
Fixed it by selecting ST_AsBinary(geom) in the query.
