### ISSUE TITLE
init.py

### ISSUE THREAD

**Issue by ivangorelow** [mapzen/tileserver#39]
I have errors in scrypt init.py:

`Traceback (most recent call last):
  File "/home/user01/tileserver/tileserver/__init__.py", line 195, in __call__
    response = self.handle_request(request)
  File "/home/user01/tileserver/tileserver/__init__.py", line 290, in handle_request
    coord, self.layer_config.all_layers)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/query.py", line 206, in __call__
    raise async_exception
ProgrammingError: column "way_area" does not exist
LINE 6:     way_area::bigint AS area,
            ^`

`127.0.0.1 - - [12/Sep/2016 14:26:02] "GET /all/16/39619/20489.json HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/user01/tileserver/tileserver/__init__.py", line 195, in __call__
    response = self.handle_request(request)
  File "/home/user01/tileserver/tileserver/__init__.py", line 290, in handle_request
    coord, self.layer_config.all_layers)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/query.py", line 206, in __call__
    raise async_exception
ProgrammingError: relation "water_polygons" does not exist
LINE 16: FROM water_polygons t`

**Comment by rmarianski** [comment]
This looks like the database updates didn't get applied. I'd suggest starting with a fresh database and following the [data import steps](https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#set-up-database) in the wiki again.

**Comment by nvkelso** [comment]
Closing for inactivity.
